# BASIC IMPLEMENTATION OF NEURAL NETWORK

In [1]:
import pandas as pd 
import numpy as np

In [2]:
##Input array
a=np.array([[0,0],[0,1],[1,1],[1,0]])

In [3]:
print(a)

[[0 0]
 [0 1]
 [1 1]
 [1 0]]


In [4]:
a.shape

(4, 2)

In [5]:
##Output array
b=np.array([0,1,0,1])

In [6]:
b=b.reshape(4,1)
print(b)

[[0]
 [1]
 [0]
 [1]]


In [7]:
b.shape

(4, 1)

# out=w*x+b

# Assign Weights

In [8]:
weights=np.array([[.1],[.2]])

# Bias

In [9]:
bias=0.3

# Activation function


1/1+exp(-x)

In [10]:
def sigmoid(x):
    return 1/1+np.exp(-x)
    

In [11]:
def der_sig(x):
    return sigmoid(x)*(1-sigmoid(x))

In [12]:
for i in range(1000):
    input_value=a
    weighted_sum=np.dot(input_value,weights)+bias
    first_output=sigmoid(weighted_sum)
    
    error=first_output-b
    total_error=np.square(np.subtract(first_output,b)).mean()
    
    first_der=error
    second_der=der_sig(first_output)
    derivative=first_der*second_der
    
    t_input=a.T
    final_der=np.dot(t_input,derivative)
    
    #weights update
    weights=weights-0.05*final_der
    
    #update bias
    for i in derivative:
        bias=bias-0.05*i
print("Updated weights: ",weights)
print("Updated bias: ",bias)
    
    
print(total_error)
print(final_der)

Updated weights:  [[25.3607106 ]
 [25.45187206]]
Updated bias:  [50.73213758]
0.5
[[-0.50321472]
 [-0.50321472]]


In [13]:
# Convergence theorem to reduce cost function
# const=cost-learning_rate(slope)
# if negative slope add
# if positive slope subtract

In [14]:
pred=np.array([[0,1]])
res=np.dot(pred,weights)+bias
result=sigmoid(res)

In [15]:
result

array([[1.]])